<PlayerDetailView 
              playerNo={focusPlayerNo}
              setPlayerNo={setFocusPlayerNo}
              playerCount={playerCount}
              players={players}
              deadPlayers={deadPlayers}
              updatePlayerInfo={updatePlayerInfo}
              updatePlayerProperty={updatePlayerProperty}
              togglePlayerAlive={togglePlayerAlive}
              chars={chars}
              nominations={nominations}
              setNominations={setNominations}
              voteHistoryMode={voteHistoryMode}
              setVoteHistoryMode={setVoteHistoryMode}
              setShowRoleSelector={setShowRoleSelector}
              deaths={deaths}
              setDeaths={setDeaths}
              currentDay={currentDay}
              setCurrentDay={setCurrentDay}
              assignmentMode={assignmentMode}
              selectedReason={selectedReason}
              selectedProperty={selectedProperty}
              onPlayerClick={handlePlayerClick}
              setAssignmentMode={setAssignmentMode}
              setSelectedReason={setSelectedReason}
              setSelectedProperty={setSelectedProperty}
            />